AllCops:
  Exclude:
    - bin/*
    - pkg/*
  TargetRubyVersion: 2.4
Metrics/BlockLength:
  Exclude:
    - test/*
Metrics/ClassLength:
  Max: 300
Metrics/LineLength:
  Max: 120
Metrics/ModuleLength:
  Max: 300
Metrics/MethodLength:
  Max: 20
Metrics/CyclomaticComplexity:
  Enabled: false
Style/Documentation:
  Enabled: false # TODO: renable this after documenting.
Style/MissingRespondToMissing:
  Enabled: false
Style/MethodMissingSuper:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '()'
    '%i': '()'
    '%w': '()'
Style/SafeNavigation:
  Enabled: false
