language: ruby
rvm:
- 2.3.6
- 2.4.3
- 2.5.0
deploy:
  provider: rubygems
  api_key:
    secure: nhnuLNbqAR/WWjLGWkdCLQxPSmY20prJKdmW/NbURC60GXoZFFollzwRM3TKYuRNDREMSjDYg88zv4ALTFLLEVk0PsDvgJ2u3Ib4Xci0ByS2YNqk+SdH9pFooacYBuFml11TcShAz+fQfhDFfnHVi1R/qPDwn46W9CPC59fAKRsHFzzjJNvWnl7VnCx/LeBJ4FJZlNOFEgQeRoXi9FsPGYpCquqs+0NRQjftGtlAlXbphGlSoy7hWZT7e8pDc+Del6Yavv78omXUlogf0UdCOO6Fc1fGzwhtOq8/f+4gUffQMWJq0nCkWzMm2zna8WQ97IxJ1AWrH2bcnN0jnwzoq6LVu8/3WNtdW0U0rBAwktXFxJmjJHJsoXaEXpAlFaR4MEgosNm6HwXxtPLuKtyLQ5kfDRMfCkNJcEPfB6tjpOgwQMMaoBS2HbXjFPqjfa945pF1jzGFL1dlZhFsroIV17obHhfYGeSSWt4Th2+a49rErxvtaLPtLRTRfk9aYOJmbexBIerHVDJSDIrN/IJMW60UIi7L7g87mGcvbqAphdD57Go1AAhvdWeLcJdbgCeuyf7fVHf5B+CWifekgA+1PiYIFdqGKqNr8P5nKfa6tuSwKcT/5oCYgn8juJp5GQQPRvIP4KwpUoDYkEDLPg/y3jkamTzqwtckwXyt6elPLF0=
  gem: esi
  on:
    tags: true
    repo: dhiemstra/esi
