language: ruby
sudo: false
cache: bundler
rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

deploy:
  provider: rubygems
  api_key:
    secure: A5FDVMEgvh31HqltJMaCgzXW72SeryyMSVBpp/zSHngXYufXLGRU3KUIeEJ6uc8S7AEeFBqBRTi9384FuVevz9rP5N0X1S4NiQBCItaKjPahhj4smY9LVIT3MV4vLL4RWOfKvgnGuUsO+tnBOpah+cAy0n55TGTmFI9f+hLk7yfyKPH9GYRyZgYCFC8t3cBxrZbMn2EXRRc8M43Jn5UalHb2yVmtErqJWTg0qXNgIG6b4IbDJVlbTGLjOc3NVaPC9sDZLQz2MRTNsmxkhUJ2gZTbC75mnrazBwkNW/hoANAwbNcEh2r0t4OduVcP5aBKl3/cRIIN+CucXuYbp+vTUV0rrJe/S3uRanKYcupy8d5cNE1zvzD1YJ/MvWmHljNOaNziRzLT7/W3emp4Rrc8l/s9qJ0FiEOdhx3+BlqOkAJVSMGuZLJM5kgaMGZaKhhH7QOWGh5uxJbKG3DeKwjicPFb0Olh3lj50AEG9J1RkOwAECYMfyOS8A2Vwks0Q7yhIw09oyoF0NLMyBBmhgo+kjGhXJD+lgjNeQoE3HzrwtUpiooPdLwqhu0AVyKcNARoNiI2+3Xbu+fgYGWZ6QnFqfLDrgM1fjays0r5FfMGrDWrEcH5wB13SC7x92hho4rtGo8bEuuPqpl9Xf2eWUF4gXTGopyBoR+kKvBtteU5jNI=
  gem: esi
  on:
    tags: true
    repo: dhiemstra/esi
